osx_image: xcode10.2
language: objective-c

notifications:
  email: false

 branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

cache: cocoapods

before_install:
    - gem install cocoapods -v '~> 1.7.0' --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

jobs:
  include:
    - stage: lint
      script:
        - pod lib lint --allow-warnings

    - stage: test
      script:
        - rm -rf ~/Library/Developer/Xcode/DerivedData/
        - cd Demo
        - pod install
        - xcodebuild clean build -workspace XYChart.xcworkspace -scheme 'XYChart' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c

    - stage: deploy
      if: tag IS present
      before_script:
        - echo 'current tag -> $TRAVIS_TAG'
        - sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" XYChart.podspec
      script:
        - set -eo pipefail
        - pod trunk push --verbose --allow-warnings | ruby -e 'ARGF.each{ print "." }'
